#!/bin/sh

WAREHOUSE_HOST=${WAREHOUSE_HOST:-"127.0.0.1"}
WAREHOUSE_PORT=${WAREHOUSE_PORT:-"12345"}
MIN_VALUE=${MIN_VALUE:-"-60"}
MAX_VALUE=${MAX_VALUE:-"60"}
SLEEP_INTERVAL=${SLEEP_INTERVAL:-"1"}
SENSOR_ID=${SENSOR_ID:-"UNKNOWN"}

while true
do
  TEMP=$((RANDOM % (MAX_VALUE - MIN_VALUE + 1) + MIN_VALUE))
  echo "sensor_id=$SENSOR_ID; value=$TEMP" | nc -u -w0 $WAREHOUSE_HOST $WAREHOUSE_PORT
  sleep $SLEEP_INTERVAL
done