services:
  t1_sensor:
    build:
      context: ./sensor-simulator
    environment:
      # - WAREHOUSE_HOST=host.docker.internal
      - WAREHOUSE_HOST=measurements-warehouse
      - WAREHOUSE_PORT=3344
      - MAX_VALUE=50
      - MIN_VALUE=-5
      - SLEEP_INTERVAL=3
      - SENSOR_ID=t1
    mem_limit: 10M

  h1_sensor:
    build:
      context: ./sensor-simulator
    environment:
      # - WAREHOUSE_HOST=host.docker.internal
      - WAREHOUSE_HOST=measurements-warehouse
      - WAREHOUSE_PORT=3355
      - MAX_VALUE=100
      - MIN_VALUE=0
      - SLEEP_INTERVAL=3
      - SENSOR_ID=h1
    mem_limit: 10M
  
  measurements-warehouse:
    build:
      context: ./measurements-warehouse
      dockerfile: Dockerfile
    ports:
      - "3344:3344"
      - "3355:3355"
    environment:
      KAFKA_BOOTSTRAP_BROKERS: broker:29092
      LOG_LEVEL: DEBUG
    depends_on:
      - broker

  central-service:
    build:
      context: ./central-service
      dockerfile: Dockerfile
    environment:
      KAFKA_BOOTSTRAP_BROKERS: broker:29092
      LOG_LEVEL: DEBUG
      THRESHOLD_TEMPERATURE: 35
      THRESHOLD_HUMIDITY: 50
    depends_on:
      - broker

  broker:
    image: confluentinc/cp-kafka:7.7.0
    hostname: broker
    container_name: broker
    ports:
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://broker:29092,CONTROLLER://broker:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      CLUSTER_ID: '7h4NQID4SiW5yh5DIvl3wQ'
  
  control-center:
    image: confluentinc/cp-enterprise-control-center:7.7.0
    hostname: control-center
    container_name: control-center
    depends_on:
      - broker
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'broker:29092'
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      CONFLUENT_METRICS_TOPIC_REPLICATION: 1
      PORT: 9021